site_name: Linuxpad Docs
nav:
  - Home: index.md
  - About: about.md
  - Docker Containers:
      - Overview: docker-containers.md
      - Adguard: adguard.md
      # Additional Docker container pages...
  - Networking:
      - Overview: networking-overview.md
      - GlusterFS: glusterfs.md
  # Additional sections...

theme:
    name: material
    locale: en
    #custom_dir: overrides
    features:
      - navigation.tracking
      - navigation.top
      - search.suggest
      - search.highlight
      - search.suggest
      - search.highlight
    palette:
      - scheme: default
        toggle:
          icon: material/toggle-switch-off-outline
          name: Switch to dark mode
      - scheme: slate
        toggle:
          icon: material/toggle-switch
          name: Switch to light mode
          primary: green
          accent: ambe
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  # Additional Markdown extensions...
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
   - toc:
      permalink: true
      toc_depth: 4
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.snippets  
  - attr_list
  # More pymdownx extensions...
extra_css:
  - css/extra.css
  - css/prism.css
extra_javascript:
  - js/prism.js

extra:
  analytics:
    provider: google
    property: G-1XXXXXX
