site_name: Linuxpad
site_author: Nana Oware Personal Blog
site_description: A List of Linux Tutorials in devops world
docs_dir: docs/

copyright: Copyright &copy; 2019 - 2024 Linuxpad
repo_name: 'home-lab'
repo_url: https://github.com/dagyepong
use_directory_urls: true
nav:
  - Home: index.md
  - Docker Containers:
      - Ghost Blog: ghost.md
      - Code-Server: code-server.md
      - Traefik: traefik.md
      - Open-Resume: open-resume.md
      - Uptime-Kuma: uptime.md
      - Dockge: dockge.md
  - Linux Tutorials:
      - Proxomox setup: setup.md
      - Jellyfin: jellyfin.md
      - Plex: plex.md
      - File-Server: cockpit.md
  - About: about.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.top
  highlightjs: true
  hljs_languages:
    - yaml
    - python
    - shell
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/book
  favicon: docs/_media/favicon.ico
  font:
    code: Fira Mono
  language: en
  include_search_page: false
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra_css:
  - docs/stylesheets/extra.material.css
  - stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - stylesheets/tables.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.7.2/highlight.min.js
  - stylesheets/highlight.js

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      type: date
  # Deactivated due to https://github.com/tikitu/jsmin/issues/33
  # Issue in progress: https://github.com/byrnereese/mkdocs-minify-plugin/issues/15
  # - minify:
  #     minify_html: true
  #     minify_js: true

markdown_extensions:
  - mdx_truly_sane_lists
  - smarty
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - fontawesome_markdown
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      separator: "-"
      # permalink: "#"
      permalink: true
      baselevel: 3
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: 'ansible_collections/arista/cvp/'